apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2026-03-04T14:49:21Z"
  generation: 53
  name: nginx
  namespace: argocd
  resourceVersion: "9921333327"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |
        controller:
          replicaCount: 2
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                      - ingress-nginx
                  topologyKey: "kubernetes.io/hostname"
        admissionWebhooks:
          patch:
            nodeSelector: {}
            tolerations: []
    path: charts/ingress-nginx
    repoURL: https://github.com/kubernetes/ingress-nginx
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
      limit: 3
